bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('store.urls')),
    url(r'^admin/', admin.site.urls),
]

store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^insert/$',views.insert,name='insert'),
    url(r'^delete/$',views.delete,name='delete'),
    url(r'^update/$',views.update,name='update'),
]

store/models.py
from django.db import models

# Create your models here.
class Book(models.Model) :
    book_id = models.PositiveIntegerField(primary_key=True)
    isbn = models.PositiveIntegerField()
    book_name = models.CharField(max_length=200)
    price = models.FloatField()
    author = models.CharField(max_length=200)

store/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Book

# Create your views here.
def index(request) :
    book_list = Book.objects.all()
    try :
        book = Book.objects.get(book_id=request.session['book_id_update'])
        del request.session['book_id_update']
    except KeyError :
        book = None
    return render(request,'index.html',{'book_list':book_list,'update_book':book})

def insert(request) :
    book_id = request.POST['book_id']
    isbn = request.POST['isbn']
    book_name = request.POST['book_name']
    price = request.POST['price']
    author = request.POST['author']
    book = Book.objects.create(book_id=book_id,isbn=isbn,book_name=book_name,price=price,author=author)
    book.save()
    return HttpResponseRedirect(reverse('store:index'))

def delete(request) :
    book_id = request.POST['book_id']
    book = Book.objects.get(book_id=book_id)
    Book.delete(book)
    return HttpResponseRedirect(reverse('store:index'))

def update(request) :
    try :
        book = Book.objects.get(book_id=request.POST['book_id_update'])
        book.book_id = request.POST['book_id']
        book.isbn = request.POST['isbn']
        book.book_name = request.POST['book_name']
        book.price = request.POST['price']
        book.author = request.POST['author']
        book.save()
    except KeyError :
        request.session['book_id_update'] = request.POST['book_id_update']
    return HttpResponseRedirect(reverse('store:index'))

store/templates/index.html
<!Doctype html>
<html>
  <header>
    <meta charset="utf-8">
    <title>Book Store</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"
  </header>
  <body>
    <div class="container">
      <div class="page-header">
        <h1>Book Store</h1>
      </div>
    </div>
    <div class="jumbotron">
      <div class="container">
        <h2>Insert New Book</h2>
        <form action="{% url 'store:insert' %}" method="POST" class="form-horizontal">
          {% csrf_token %}
          <div class="form-group">
            <label  for="book_id" class="col-sm-2 control-label">Book ID</label>
            <div class="col-sm-10">
              <input type="number" name="book_id" id="book_id"  class="form-control" placeholder="Input Book ID ...">
            </div>
          </div>
          <div class="form-group">
            <label  for="isbn" class="col-sm-2 control-label">ISBN</label>
            <div class="col-sm-10">
              <input type="number" name="isbn" id="isbn"   class="form-control" placeholder="Input ISBN ...">
            </div>
          </div>
          <div class="form-group">
            <label  for="book_name" class="col-sm-2 control-label">Book Name</label>
            <div class="col-sm-10">
              <input type="text" name="book_name" id="book_name"  class="form-control" placeholder="Input Book Name ...">
            </div>
          </div>
          <div class="form-group">
            <label  for="price" class="col-sm-2 control-label">Price</label>
            <div class="col-sm-10">
              <input type="number" name="price" id="price"  class="form-control" placeholder="Input Price ..." >
            </div>
          </div>
          <div class="form-group">
            <label  for="author" class="col-sm-2 control-label">Author</label>
            <div class="col-sm-10">
              <input type="text" name="author" id="author"  class="form-control" placeholder="Input Author ..." >
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="INSERT" class="btn btn-success">
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="container">
      <h2>Book List</h2>
      <table class="table table-striped">
        <!-- table header -->
        <tr>
          <th>Book ID</th>
          <th>ISBN</th>
          <th>Book Name</th>
          <th>Price</th>
          <th>Author</th>
          <th></th>
          <th></th>
        </tr>
        <!-- iterating inserting row in table -->
        {% for book in book_list %}
          <tr>
            <form action="{% url 'store:update' %}" method="post">
              {% csrf_token %}
              {% if update_book == book %}
                <td><input type="number" name="book_id" value="{{ book.book_id }}" class="form-control" ></td>
                <td><input type="number" name="isbn" value="{{ book.isbn }}" class="form-control" ></td>
                <td><input type="text" name="book_name" value="{{ book.book_name }}" class="form-control" ></td>
                <td><input type="number" name="price" value="{{ book.price }}" class="form-control" ></td>
                <td><input type="text" name="author" value="{{ book.author }}" class="form-control" ></td>
              {% else %}
                <td>{{ book.book_id }}</td>
                <td>{{ book.isbn }}</td>
                <td>{{ book.book_name }}</td>
                <td>{{ book.price }}</td>
                <td>{{ book.author }}</td>
              {% endif %}
              <td><button name="book_id_update" value="{{ book.book_id }}" class="btn btn-info">Update</button></td>
            </form>
            <td>
              <form action="{% url 'store:delete' %}" method="post">
                {% csrf_token %}
                <button name="book_id" value="{{ book.book_id }}" class="btn btn-danger">Delete</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>